#cloud-config

package_update: true
package_upgrade: true
packages:
  - build-essential 
  - curl 
  - nginx 
  - npm

users:
  - name: ${user_name}
    shell: /bin/bash
    groups: users, admin, sudo
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_import_id:
      - gh:${github_user} 
services:
  nginx:
    enabled: true
    restart: on-failure

runcmd:
  - npm install -g nvm
  - npm install -g typescript
  - npm install -g pm2
  - npm install -g yarn