#cloud-config

package_update: true
package_upgrade: true
packages:
  - build-essential 
  - curl 
  - nginx 
  - npm
  - redis
  - certbot

hostname: ${hostname}

users:
  - name: ${user_name}
    shell: /bin/bash
    groups: users, admin, sudo
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_import_id:
      - gh:${github_user} 
services:
  nginx:
    enabled: true
    restart: on-failure

runcmd:
  - mkdir -p /opt/nvm
  - wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | NVM_DIR=/opt/nvm bash
  - printf '\nexport NVM_DIR="/opt/nvm"\n[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"\n' >> /etc/bash.bashrc
  - printf '\nexport NVM_DIR="/opt/nvm"\n[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"\n' >> /home/${user_name}/.bashrc  
  - npm install -g typescript
  - npm install -g pm2
  - npm install -g yarn
  - mkdir -p /opt/docker
  - mkdir -p /opt/www
  - chgrp -R ${user_name} /opt/docker
  - chmod -R 776 /opt/docker
  - chgrp -R ${user_name} /opt/www
  - chmod -R 776 /opt/www

